//go:build darwin

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/schneik80/fusionlocalserver/internal/fusionlink"
)

// macOS does not hand a URL scheme launch to a program on its command line.
//
// This is the whole reason this file looks the way it does, and it is worth
// stating plainly because the obvious implementation is wrong in a way that
// still *reports success*. Launch Services resolves a scheme to a bundle, starts
// it, and then delivers the URL as a `kAEGetURL` Apple Event. A process with no
// run loop never receives it. So a bundle whose executable is
//
//	#!/bin/sh
//	exec /usr/local/bin/fls-helper "$@"
//
// — which is what this file used to write — runs fls-helper with *no arguments*
// on every Open and Insert. It printed usage to a terminal that does not exist
// and exited. Registration looked fine, pairing looked fine, and every button
// failed. Windows ("%1") and Linux (Exec=… %u) both pass argv, which is why they
// were unaffected.
//
// Receiving the Apple Event directly would mean linking AppKit through cgo,
// which would break the cross-compiled `make helper` build for every platform.
// The one mechanism that does not is an AppleScript applet: `on open location`
// is handed the URL, and osacompile ships with every macOS. The package already
// shells out to osascript for notify(), so this stays in keeping.

const appBundleName = "Fusion Local Server Helper.app"

const bundleIdentifier = "com.schneik80.fusionlocalserver.helper"

// targetMarkerName holds the path this bundle dispatches to, in plain text, so
// schemeRegistration can answer "does this registration point at me?" without
// decompiling main.scpt. Its first line is a format version: bumping it is how
// a future change to the bundle's internals marks every existing registration
// stale, so `status` says "re-run register" instead of silently claiming health.
const targetMarkerName = "fls-target"

const targetMarkerVersion = "2"

const lsregister = "/System/Library/Frameworks/CoreServices.framework/Frameworks/" +
	"LaunchServices.framework/Support/lsregister"

func bundlePath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, "Applications", appBundleName), nil
}

// appletSource renders the applet's AppleScript.
//
// exe is baked in as a literal because the applet has to keep working after the
// user's PATH changes, but the URL is *not*: this_URL is whatever web page
// navigated to the scheme, so it is passed through AppleScript's `quoted form
// of` and never concatenated into the shell string raw. That is the injection
// boundary of this whole file.
//
// The call is backgrounded, and deliberately so. One launch can take up to
// launchTimeout (45s) waiting on Fusion, and a synchronous `do shell script`
// would hold the applet open for all of it — blocking a second Open behind the
// first, and turning the helper's non-zero exit into an AppleScript error
// dialog stacked on top of the specific message the helper already showed. The
// wrapping `try` covers the case where the shell call itself fails.
func appletSource(exe string) string {
	return `-- Generated by fls-helper register. Do not edit.
--
-- This applet exists only because macOS delivers a URL scheme launch as an
-- Apple Event, which the fls-helper binary cannot receive. Its sole job is to
-- hand that URL to fls-helper as an argument.

on run
	-- Double-clicked in Finder. This is a protocol handler, not something to
	-- launch, so do nothing rather than fail.
end run

on open location this_URL
	try
		do shell script quoted form of ` + appleScriptString(exe) + ` & " " & quoted form of this_URL & " >/dev/null 2>&1 &"
	end try
end open location
`
}

func registerScheme() error {
	exe, err := os.Executable()
	if err != nil {
		return fmt.Errorf("locating this program: %w", err)
	}
	exe, err = filepath.EvalSymlinks(exe)
	if err != nil {
		return fmt.Errorf("resolving this program's path: %w", err)
	}
	bundle, err := bundlePath()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(bundle), 0755); err != nil {
		return fmt.Errorf("creating %s: %w", filepath.Dir(bundle), err)
	}

	// Build beside the destination, then rename into place: a rename is only
	// atomic within a filesystem, and a half-written .app that Launch Services
	// had already noticed would be worse than no .app at all.
	staging, err := os.MkdirTemp(filepath.Dir(bundle), ".fls-helper-register-")
	if err != nil {
		return fmt.Errorf("creating a staging directory: %w", err)
	}
	defer os.RemoveAll(staging)

	src := filepath.Join(staging, "fls-helper.applescript")
	if err := os.WriteFile(src, []byte(appletSource(exe)), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", src, err)
	}
	built := filepath.Join(staging, appBundleName)
	if out, cerr := exec.Command("osacompile", "-o", built, src).CombinedOutput(); cerr != nil {
		return fmt.Errorf("compiling the handler app: %w: %s", cerr, strings.TrimSpace(string(out)))
	}

	if err := patchBundlePlist(built); err != nil {
		return err
	}

	marker := filepath.Join(built, "Contents", "Resources", targetMarkerName)
	if err := os.WriteFile(marker, []byte(targetMarkerVersion+"\n"+exe+"\n"), 0644); err != nil {
		return fmt.Errorf("writing %s: %w", marker, err)
	}

	// osacompile ad-hoc signs its output, so editing Info.plist afterwards
	// invalidates the seal (`codesign -v` reports "plist or signature have been
	// modified"). That does not stop the applet from launching — verified on
	// macOS 26 / arm64, and Gatekeeper only assesses quarantined apps — but
	// repairing it is free when the tooling is there. Best effort by design:
	// codesign is gated behind the Command Line Tools, and requiring a
	// multi-gigabyte developer download to register a URL scheme would be
	// absurd.
	_ = exec.Command("codesign", "--force", "--sign", "-", built).Run()

	// Drop the old registration before the bundle it named disappears, or
	// Launch Services keeps serving a cached record of a directory that no
	// longer exists.
	if _, serr := os.Stat(bundle); serr == nil {
		runLSRegister("-u", bundle)
		if err := os.RemoveAll(bundle); err != nil {
			return fmt.Errorf("replacing %s: %w", bundle, err)
		}
	}
	if err := os.Rename(built, bundle); err != nil {
		return fmt.Errorf("installing %s: %w", bundle, err)
	}

	// Nudge Launch Services to pick up the new bundle immediately; without it
	// the scheme only starts working after the system rescans on its own.
	runLSRegister("-f", bundle)
	return nil
}

// localNetworkPurpose is required, not decorative.
//
// From macOS 15 an app must hold Local Network permission to open a connection
// to a host on the LAN, and the system will not prompt for it unless the app
// declares a purpose string. The whole reason the helper exists is that the
// server is on another machine — usually the local network — so without this key
// every launch fails at the first HTTPS call with a bare "cannot reach", while
// the identical binary run from a terminal succeeds because Terminal holds the
// permission instead. That divergence is very hard to read as a permissions
// problem, which is precisely why it is worth a comment this long.
const localNetworkPurpose = "Fusion Local Server Helper connects to the fusionlocalserver " +
	"you paired with, which usually runs on your local network."

// patchBundlePlist adds what osacompile cannot: the scheme claim itself, our
// identity, the accessory-app flag that keeps a protocol handler out of the
// Dock, and the Local Network purpose string.
func patchBundlePlist(bundle string) error {
	info := filepath.Join(bundle, "Contents", "Info.plist")
	urlTypes, err := json.Marshal([]map[string]any{{
		"CFBundleURLName":    "Fusion Local Server",
		"CFBundleURLSchemes": []string{fusionlink.Scheme},
	}})
	if err != nil {
		return err
	}
	for _, kv := range []struct {
		key   string
		value []string
	}{
		{"CFBundleName", []string{"-string", "Fusion Local Server Helper"}},
		{"CFBundleIdentifier", []string{"-string", bundleIdentifier}},
		{"CFBundleShortVersionString", []string{"-string", version}},
		{"LSUIElement", []string{"-bool", "true"}},
		{"NSLocalNetworkUsageDescription", []string{"-string", localNetworkPurpose}},
		{"CFBundleURLTypes", []string{"-json", string(urlTypes)}},
	} {
		if err := plistPut(info, kv.key, kv.value...); err != nil {
			return err
		}
	}
	return nil
}

// plistPut sets one key, removing any existing value first. plutil's -insert
// fails when the key already exists and -replace fails when it does not, so
// remove-then-insert is the only spelling that works for both — and osacompile
// writes some of these keys and not others.
func plistPut(info, key string, value ...string) error {
	_ = exec.Command("plutil", "-remove", key, info).Run()
	args := append([]string{"-insert", key}, value...)
	args = append(args, info)
	if out, err := exec.Command("plutil", args...).CombinedOutput(); err != nil {
		return fmt.Errorf("setting %s in Info.plist: %w: %s", key, err, strings.TrimSpace(string(out)))
	}
	return nil
}

func runLSRegister(args ...string) {
	if _, err := os.Stat(lsregister); err != nil {
		return
	}
	_ = exec.Command(lsregister, args...).Run()
}

func unregisterScheme() error {
	bundle, err := bundlePath()
	if err != nil {
		return err
	}
	runLSRegister("-u", bundle)
	if err := os.RemoveAll(bundle); err != nil {
		return fmt.Errorf("removing %s: %w", bundle, err)
	}
	return nil
}

// schemeRegistration reports whether a launch would actually reach this binary.
// It checks the three things that can independently be wrong: the bundle claims
// the scheme, it is an applet (so it can receive the Apple Event at all), and it
// dispatches to the path this binary is running from.
func schemeRegistration() (string, schemeState, string) {
	bundle, err := bundlePath()
	if err != nil {
		return "", schemeAbsent, ""
	}
	if _, serr := os.Stat(bundle); serr != nil {
		return "", schemeAbsent, ""
	}

	plist, err := os.ReadFile(filepath.Join(bundle, "Contents", "Info.plist"))
	if err != nil || !strings.Contains(string(plist), "<string>"+fusionlink.Scheme+"</string>") {
		return bundle, schemeStale, "the app there does not claim the scheme"
	}
	// The applet's compiled script is what receives the URL. Its absence is the
	// signature of the shim-based bundle written by pre-release fls-helper builds.
	if _, serr := os.Stat(filepath.Join(bundle, "Contents", "Resources", "Scripts", "main.scpt")); serr != nil {
		return bundle, schemeStale,
			"it was registered by an older fls-helper and cannot receive URLs from macOS"
	}

	marker, err := os.ReadFile(filepath.Join(bundle, "Contents", "Resources", targetMarkerName))
	if err != nil {
		return bundle, schemeStale, "it was registered by an older fls-helper"
	}
	fields := strings.Split(strings.TrimSpace(string(marker)), "\n")
	if len(fields) != 2 || fields[0] != targetMarkerVersion {
		return bundle, schemeStale, "it was registered by a different version of fls-helper"
	}
	target := fields[1]

	// A registration pointing at some other copy of the helper is not this
	// binary's registration, and saying "registered" would send someone
	// debugging in the wrong direction.
	exe, err := os.Executable()
	if err == nil {
		if resolved, rerr := filepath.EvalSymlinks(exe); rerr == nil {
			exe = resolved
		}
		if exe != target {
			return bundle, schemeStale,
				fmt.Sprintf("it dispatches to %s, not to this binary at %s", target, exe)
		}
	}
	if _, serr := os.Stat(target); serr != nil {
		return bundle, schemeStale, fmt.Sprintf("it dispatches to %s, which no longer exists", target)
	}
	return bundle, schemeGood, ""
}
